networks:
  my_bridge:
    driver: bridge
    ipam:
      config:
      - gateway: 172.19.0.1
        subnet: 172.19.0.0/24
      driver: default
    name: my-bridge

services:
  iyuuplus:
    container_name: iyuuplus
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-cqS", "--spider", "http://127.0.0.1:8787/"]
    image: kissice/iyuuplus
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 5m
    networks:
      my_bridge:
        aliases:
        - iyuuplus
    ports:
    - "3131:3131"
    - "8787:8787"
    - "8788:8788"
    restart: always
    volumes:
    - iyuuplus:/var/www/iyuuplus:rw

  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    environment:
      MYSQL_DATABASE: iyuu
      # MYSQL_INITDB_SKIP_TZINFO:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_USER: iyuu
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    image: mysql:8.4
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 5m
    networks:
      my_bridge:
        aliases:
        - mysql
    restart: always
    secrets:
    - mysql-password
    - mysql-root-password
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - mysql:/var/lib/mysql:rw

secrets:
  mysql-password:
    file: ~/.docker/datas/mysql/mysql-password
  mysql-root-password:
    file: ~/.docker/datas/mysql/mysql-root-password

volumes:
  iyuuplus:
    name: iyuuplus
  mysql:
    name: mysql
