name: Keepalive Workflow CI

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
