name: MongoDB Docker Image Based On Alpine CI

on:
  workflow_dispatch:
    schedule:
      - cron: "0 1 * * *"

env:
  MONGODB_VERSIONS: "['4.0', '3.6']"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if Alpine update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: alpine:latest
          image: ${{ secrets.DOCKER_USERNAME }}/mongo:3.6
          platforms: linux/amd64

  build:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.needs-updating == 'true'

    strategy:
      matrix:
        version: ${{ fromJson(env.MONGODB_VERSIONS) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          REPOSITORY=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=mongo
          VERSION=${{ matrix.version }}
          TAGS="${REPOSITORY}/${IMAGE_NAME}:${VERSION}"
          echo "build_args=MONGO_BUILD_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MongoDB's Docker image (based on Alpine)
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.prepare.outputs.image_name }}
          file: ./${{ steps.prepare.outputs.image_name }}/alpine/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
