name: MongoDB Docker Image Based On Amazon Linux 2 CI

on:
  workflow_dispatch:
  schedule:
    - cron: "20 1 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if Amazon Linux 2 update available
        id: run
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: library/amazonlinux:2
          image: ${{ secrets.DOCKER_USERNAME }}/mongo:amzn2
        continue-on-error: true
        if: github.event_name == 'schedule'
      - name: Check on result
        id: check
        run: |
          if [[ ${{ steps.run.outcome }} == 'success' ]]; then
            echo "needs-updating=${{ steps.run.outputs.needs-updating }}" >> $GITHUB_OUTPUT
          else
            echo "needs-updating=true" >> $GITHUB_OUTPUT
          fi
        if: github.event_name == 'schedule'

  build:
    needs: check
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'schedule' ||
      needs.check.outputs.needs-updating == 'true'

    strategy:
      matrix:
        version: ["8.0", "7.0", "6.0", "5.0", "4.4", "4.2", "4.0", "3.6"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          REPOSITORY=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=mongo
          VERSION=${{ matrix.version }}
          TAGS="${REPOSITORY}/${IMAGE_NAME}:${VERSION}-amzn2"
          if [[ ${{ matrix.version }} == '8.0' ]]; then
            TAGS+=",${REPOSITORY}/${IMAGE_NAME}:amzn2"
          fi
          if [[ ${{ matrix.version }} =~ ^(4\.4|4\.2|4\.0|3\.6)$ ]]; then
            TAGS+=",${REPOSITORY}/${IMAGE_NAME}:${VERSION}"
          fi
          PLATFORMS=linux/amd64,linux/arm64/v8
          if [[ ${{ matrix.version }} =~ ^(4\.0|3\.6)$ ]]; then
            PLATFORMS=linux/amd64
          fi
          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "build_args=MONGO_BUILD_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MongoDB's Docker image (based on Amazon Linux 2)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.prepare.outputs.image_name }}
          file: ./${{ steps.prepare.outputs.image_name }}/amazon-linux/2/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ steps.prepare.outputs.platforms }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
