name: Docker PHP-FPM Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        default: "8.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          REPOSITORY=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=php
          VERSION=${{ github.event.inputs.version }}
          TAGS="${REPOSITORY}/${IMAGE_NAME}:${VERSION}-fpm"
          echo "build_args=PHP_BUILD_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (PHP 5.6) Docker image
        if: github.event.inputs.version == '5.6'
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.prepare.outputs.image_name }}/${{ steps.prepare.outputs.version }}
          file: ./${{ steps.prepare.outputs.image_name }}/${{ steps.prepare.outputs.version }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Build and push (PHP 7.0+) Docker image
        if: github.event.inputs.version != '5.6'
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.prepare.outputs.image_name }}/${{ steps.prepare.outputs.version }}
          file: ./${{ steps.prepare.outputs.image_name }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
